name: 'kevin_leptons/ssh_action'
description: Execute commands at remote host by SSH
author: Kevin Leptons
inputs:
    host:
        description: URI refers to remote host like `user@host`
        required: true
    key:
        description: Private SSH key to authenticate
        required: true
    command:
        description: Command to execute, Bash syntax
        required: true
runs:
    using: 'docker'
    image: dockerfile
    args:
        - ${{ inputs.command }}
branding:
    icon: 'terminal'
    color: 'green'
